import Head from 'next/head'
import Image from 'next/image'
import AboutUs from '../Components/Layouts/AboutUs'
import Advert from '../Components/Layouts/Advert'
import Clients from '../Components/Layouts/Clients'
import Designer from '../Components/Layouts/Designer'
import Help from '../Components/Layouts/Help'
import HeroSection from '../Components/Layouts/HeroSection'
import NavBar from '../Components/Layouts/NavBar'
import Footer from '../Components/Layouts/Footer'


export default function Home() {
  return (
<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar style=''/>
      <HeroSection/>
      <AboutUs/>
      <Clients/>
      <Advert/>
      <Designer/>
      <Help/>
      {/* <Footer/> */}
      </>
      

      
  )
}
