import Head from 'next/head'
import Image from 'next/image'
import AboutUs from '../Components/Layouts/AboutUs'
import HeroSection from '../Components/Layouts/HeroSection'
import NavBar from '../Components/Layouts/NavBar'


export default function Home() {
  return (
<>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar style='md:absolute md:w-full top-0'/>
      <HeroSection/>
      <AboutUs/>
      </>
      

      
  )
}
